

import { IFormObject } from '../interfaces/form-object.interface';

export const TaskGridDetailForm: IFormObject = {
    
    selected: {
        id: 1,
        label: 'selected',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    project: {
        id: 1,
        label: 'project',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    taskName: {
        id: 1,
        label: 'taskName',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    type: {
        id: 1,
        label: 'type',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    sowIssueNo: {
        id: 1,
        label: 'sowIssueNo',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    isBillable: {
        id: 1,
        label: 'isBillable',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },

    billingType: {
        id: 1,
        label: 'billingType',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    resName: {
        id: 1,
        label: 'resName',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    team: {
        id: 1,
        label: 'team',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    estStartDate: {
        id: 1,
        label: 'estStartDate',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    estEndDate: {
        id: 1,
        label: 'estEndDate',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    estHours: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    actEndDate: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    startTime: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    endTime: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    sprint: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    actHours: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    percentage: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    status: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },
    comments: {
        id: 1,
        label: 'estHours',
        value: '',
        type: 'text',
        validations: [],
        disabled: false,
    },


    actStartDate: {
        id: 2,
        label: 'Batch From',
        value:'',
        type: 'DateField',
        validations: [ ],
        disabled: false,
    },
    toDate: {
        id: 3,
        label: 'To',
        value: '',
        type: 'DateField',
        validations: [
            // {
            //     validator: 'invalidDate',
            //     value: false,
            //     message: 'ERROR_MSG.29394',
            // },
        ],
        disabled: false,
    },
    
};
